name: Deploy to AWS S3

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps


   
      
      
      - name: Build app
        env:
          BACKEND_API:  ${{ secrets.BACKEND_API }} 
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
        run: npm run build
